CREATE TABLE IF NOT EXISTS products (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT DEFAULT NULL,
  price DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  sale_price DECIMAL(10, 2) DEFAULT NULL,
  category VARCHAR(100) DEFAULT NULL,
  sku VARCHAR(100) DEFAULT NULL,
  stock INT DEFAULT 0,
  status ENUM('draft', 'publish') DEFAULT 'draft',
  source ENUM('admin', 'woocommerce') DEFAULT 'admin',
  image_url TEXT DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
